import getStores from "@/actions/getStore";
import DashboardNavbar from "@/components/dashboardNavbar";
import MobileSidebar from "@/components/mobileSidebar";
import Sidebar from "@/components/sidebar";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const store = await getStores();
	return (
		<div className="">
			<div className="hidden h-full md:flex md:w-72 md:flex-col md:fixed md:inset-y-0  bg-gray-900">
				<Sidebar name={store.name} />
			</div>
			<div className="flex items-center p-4 md:hidden">
				<MobileSidebar name={store.name} />
			</div>
			<div className="md:pl-72 overflow-x-hidden">
				<div className="p-4">{children}</div>
			</div>
		</div>
	);
}
